### ISSUE TITLE
Always getting "Unknown artist"

### ISSUE THREAD

**Issue by dwmcqueen** [git-developer/marvyn#5]
I have tried a few examples and I always get unknown artist on any CD.

**Comment by git-developer** [comment]
I had no problems when I tried, but it's been a few months ago.

Maybe the problem is that freedb has been shutdown in 03/2020. You could try to configure a different CDDB URL or CDDB method in the abcde configuration, by default in `/opt/docker/marvyn/data/.abcde.conf`. The abcde manual with details can be found [here](https://linux.die.net/man/1/abcde). Maybe the [Ubuntu Wiki](https://wiki.ubuntuusers.de/abcde/) helps, too.

You could try
```CDDBURL="http://gnudb.gnudb.org/~cddb/cddb.cgi"```
or
```CDDBURL="http://freedb.dbpoweramp.com:80/~cddb/cddb.cgi"```
or
```CDDBMETHOD="musicbrainz"```

**Comment by dwmcqueen** [comment]
That was it!  This can be closed - sorry.

**Comment by git-developer** [comment]
No problem.

Would you tell me how exactly you solved the problem? I could change the [default abcde configuration](https://github.com/git-developer/marvyn/blob/develop/data/.abcde.conf) accordingly so that others may participate from your solution.

**Comment by dwmcqueen** [comment]
I went the musicbrainz route.  That seemed to work.
